# Generated by Django 2.2.5 on 2019-11-06 04:29

from django.db import migrations, models
import generateletter.models


class Migration(migrations.Migration):

    dependencies = [
        ('generateletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaletters',
            name='Visa_Letter_N',
            field=models.CharField(default='<function Visaletters.number at 0x0000025D5D8E7048>', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='visaletters',
            name='Visa_Letter_Number',
            field=models.CharField(default=generateletter.models.Visaletters.number, max_length=200),
        ),
    ]
