# Generated by Django 2.2.5 on 2019-11-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateletter', '0002_auto_20191106_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaletters',
            name='Visa_Letter_N',
            field=models.CharField(default='<function Visaletters.number at 0x000002220E533048>', editable=False, max_length=200),
        ),
    ]
