# Generated by Django 2.2.5 on 2019-11-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateletter', '0004_auto_20191108_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaletters',
            name='Visa_Letter_N',
            field=models.CharField(default='<function Visaletters.number at 0x000002C922D86438>', editable=False, max_length=200),
        ),
    ]
